a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços?', a.isspace())
print('É númerico?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanumerico?', a.isalnum())
print('É letra maiuscula?', a.isupper())
print('É minusculo?', a.islower())
print('É capitalizada?', a.istitle())